export const ADD_NAME = "ADD_NAME"
export const EDIT_NAME = "EDIT_NAME"
export const DELETE_NAME = "DELETE_NAME"
export const ADD_FOOD = "ADD_FOOD"
export const EDIT_FOOD = "EDIT_FOOD"
export const DELETE_FOOD = "DELETE_FOOD"
export const SET_FOOD_PRICE = "SET_FOOD_PRICE"
export const SET_NEW_PRICE = "SET_NEW_PRICE"
export const SET_MEMBER_VALUE = "SET_MEMBER_VALUE"

export const CALCULATE = "CALCULATE"
